enum SmartContractsActions {
  SMART_CONTRACTS_LOAD = 'SMART_CONTRACTS_LOAD',
  SMART_CONTRACTS_LOAD_SUCCESS = 'SMART_CONTRACTS_LOAD_SUCCESS',
  SMART_CONTRACTS_SET_ACTIVE_CONTRACT = 'SMART_CONTRACTS_SET_ACTIVE_CONTRACT',
  SMART_CONTRACTS_SET_ACTIVE_CONTRACT_SUCCESS = 'SMART_CONTRACTS_SET_ACTIVE_CONTRACT_SUCCESS',
  SMART_CONTRACTS_START_DEBUGGING = 'SMART_CONTRACTS_START_DEBUGGING',
  SMART_CONTRACTS_STOP_DEBUGGING = 'SMART_CONTRACTS_STOP_DEBUGGING',
}

export const SMART_CONTRACTS_LOAD = SmartContractsActions.SMART_CONTRACTS_LOAD;
export const SMART_CONTRACTS_LOAD_SUCCESS = SmartContractsActions.SMART_CONTRACTS_LOAD_SUCCESS;
export const SMART_CONTRACTS_SET_ACTIVE_CONTRACT = SmartContractsActions.SMART_CONTRACTS_SET_ACTIVE_CONTRACT;
export const SMART_CONTRACTS_SET_ACTIVE_CONTRACT_SUCCESS = SmartContractsActions.SMART_CONTRACTS_SET_ACTIVE_CONTRACT_SUCCESS;
export const SMART_CONTRACTS_START_DEBUGGING = SmartContractsActions.SMART_CONTRACTS_START_DEBUGGING;
export const SMART_CONTRACTS_STOP_DEBUGGING = SmartContractsActions.SMART_CONTRACTS_STOP_DEBUGGING;
