enum AppActions {
  APP_INIT = 'APP_INIT',
  APP_INIT_DEFAULT = 'APP_INIT_DEFAULT',
  APP_INIT_SUCCESS = 'APP_INIT_SUCCESS',
  APP_REFRESH = 'APP_REFRESH',
  APP_THEME_CHANGE = 'APP_THEME_CHANGE',
  APP_MENU_STATE_CHANGE = 'APP_MENU_STATE_CHANGE',
  APP_MENU_SIZE_CHANGE = 'APP_MENU_SIZE_CHANGE',
  APP_TOGGLE_SIDENAV = 'APP_TOGGLE_SIDENAV',
}

export const APP_INIT = AppActions.APP_INIT;
export const APP_INIT_DEFAULT = AppActions.APP_INIT_DEFAULT;
export const APP_INIT_SUCCESS = AppActions.APP_INIT_SUCCESS;
export const APP_REFRESH = AppActions.APP_REFRESH;
export const APP_THEME_CHANGE = AppActions.APP_THEME_CHANGE;
export const APP_MENU_STATE_CHANGE = AppActions.APP_MENU_STATE_CHANGE;
export const APP_MENU_SIZE_CHANGE = AppActions.APP_MENU_SIZE_CHANGE;
export const APP_TOGGLE_SIDENAV = AppActions.APP_TOGGLE_SIDENAV;

